// ignore_for_file: public_member_api_docs, sort_constructors_first, prefer_collection_literals
import 'dart:convert';

class Autogenerated {
  List<PackSticker>? packSticker;

  Autogenerated({this.packSticker});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['packSticker'] != null) {
      packSticker = <PackSticker>[];
      json['packSticker'].forEach((v) {
        packSticker!.add(PackSticker.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (packSticker != null) {
      data['packSticker'] = packSticker!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class PackSticker {
  String? urlImage; 
  String? title;
  bool? status;
  StickerChild? stickerChild;
  String? id;

  PackSticker({this.urlImage, this.title, this.status, this.stickerChild, this.id});

  PackSticker.fromJson(Map<String, dynamic> json) {
    urlImage = json['urlImage'];
    title = json['title'];
    status = json['status'];
    stickerChild = json['stickerChild'] != null ? StickerChild.fromJson(json['stickerChild']) : null;
    id = json['id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['urlImage'] = urlImage;
    data['title'] = title;
    data['status'] = status;
    if (stickerChild != null) {
      data['stickerChild'] = stickerChild!.toJson();
    }
    data['id'] = id;
    return data;
  }
}

class StickerChild {
  String? title;
  String? quantity;
  String? urlImage;

  StickerChild({this.title, this.quantity, this.urlImage});

  StickerChild.fromJson(Map<String, dynamic> json) {
    title = json['title'];
    quantity = json['quantity'];
    urlImage = json['urlImage'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['title'] = title;
    data['quantity'] = quantity;
    data['urlImage'] = urlImage;
    return data;
  }
}
