stages:
  - sync-dependencies
  - test
  - build
  - deploy

cache: &flutter_cache
  key: "$CI_PROJECT_NAME-flutter-cache"
  paths:
    - ~/.pub-cache
  policy: pull

sync_dependencies:
  stage: sync-dependencies
  image: "cirrusci/flutter:latest"
  only:
    refs:
      - main
    changes:
      - pubspec.lock
      - pubspec.yaml
  cache:
    <<: *flutter_cache
    policy: pull-push
  script:
    - flutter packages get

code_quality:
  stage: test
  image: "cirrusci/flutter:latest"
  before_script:
    - flutter pub global activate dart_code_metrics
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
  script:
    - metrics lib -r codeclimate  > gl-code-quality-report.json

build-android-apk:
  stage: build
  image: "cirrusci/flutter:latest"
  only:
    - main
  script:
   - flutter build apk 
  artifacts:
    paths:
       - build/app/outputs/flutter-apk/app-release.apk
    expire_in: 1 day

deploy-android:
  stage: deploy
  image: 
    name: banst/awscli
    entrypoint: [""]
  needs: ["build-android-apk"]
  only:
    - main
  script:
    - aws configure set region $S3_REGION
    - aws s3 cp build/app/outputs/flutter-apk/app-release.apk s3://$S3_BUCKET/isticker/app.apk
