import 'dart:convert';

import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:sticker_maker/src/views/pack_sticker/cubit/add_sticker_to_pack_state.dart';

import '../model/package_sticker_model.dart';

class AddStickerToPackCubit extends Cubit<AddStickerToPackState> {
  AddStickerToPackCubit() : super(AddStickerToPackLoading());
  bool selectedpack = false;

  List<PackSticker> listPack = [];
  List<StickerChild> sticker = [];

  Future<Autogenerated> readData() async {
    String response = await rootBundle.loadString("assets/json/data_pack_sticker.json");
    var data = await json.decode(response) as Map;
    return Autogenerated.fromJson(data.cast());
  }
  
}
