import 'dart:convert';
import 'dart:ffi';
import 'dart:io';

import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:path_provider/path_provider.dart';
import 'package:sticker_maker/src/views/pack_sticker/cubit/add_sticker_to_pack_state.dart';

import '../model/package_sticker_model.dart';

class AddStickerToPackCubit extends Cubit<AddStickerToPackState> {
  AddStickerToPackCubit() : super(AddStickerToPackLoading());
  bool selectedpack = false;
  List<PackSticker> listpack = [];
  List<String> listchild = [];

  readData() async {
    String response = await rootBundle.loadString("assets/json/data_pack_sticker.json");
    dynamic data = await json.decode(response) as Map;
    List<PackSticker> list = Autogenerated.fromJson(data).packSticker ?? [];
    emit(Readingdata(list: list));
  }

  addToPack(String pathImage) async {
    List<String> listChild = [pathImage];
    String childData = jsonEncode(listChild);
    PackSticker addToPack = PackSticker(stickerChild: [childData]);
    String addToPackDone = jsonEncode(addToPack);
    print("object add to pack ${addToPackDone}");
    emit(InsertData(listchild: addToPackDone));
  }

  createPack() {
    List<PackSticker> newPack = [PackSticker(id: '', status: false, stickerChild: [], title: '', urlImage: '')];
    String endcodeNewPack = jsonEncode(newPack);
    emit(state);
  }

  saveImage(Uint8List bytes) async {
    final Directory? extDir = await getExternalStorageDirectory();
    String dirPath = '${extDir!.path}/Documents/pictures';
    dirPath = dirPath.replaceAll("Android/data/com.intes.sticker_maker/files/", "");
    await Directory(dirPath).create(recursive: true);
    String outputPath = '$dirPath/${DateTime.now().microsecondsSinceEpoch}.png';
    // print("outputPath ${outputPath}");
    emit(AddStickerToSuccess(image: bytes));
  }
}
