// ignore_for_file: prefer_const_constructors

import "package:flutter/material.dart";
import "package:flutter/services.dart";
import "package:flutter_bloc/flutter_bloc.dart";
import "package:flutter_gen/gen_l10n/app_localizations.dart";
import "package:flutter_svg/flutter_svg.dart";
import "package:sticker_maker/src/utils/utils_index.dart";
import 'package:sticker_maker/src/views/pack_sticker/component/custom_choose_sticker.dart';
import 'package:sticker_maker/src/views/pack_sticker/cubit/add_sticker_to_pack_cubit.dart';
import 'package:sticker_maker/src/views/pack_sticker/cubit/add_sticker_to_pack_state.dart';
import 'package:sticker_maker/src/views/pack_sticker/model/package_sticker_model.dart';
import 'package:sticker_maker/src/views/pack_sticker/page/pack_library_page.dart';
import "package:sticker_maker/src/views/views_index.dart";

class AddToPackPage extends StatefulWidget {
  AddToPackPage({
    super.key,
    this.imageFile,
  });
  final Uint8List? imageFile;

  @override
  State<AddToPackPage> createState() => _AddToPackPageState();
}

class _AddToPackPageState extends State<AddToPackPage> {
  bool showbtn = false;
  late AddStickerToPackCubit cubit;
  int countSelectedPack = 0;
  int selected = 0;
  Uint8List? imagePath;
  Autogenerated? autoGenResponse;
  List<PackSticker>? listPack;
  List<String>? stickerChild;

  @override
  void initState() {
    cubit = AddStickerToPackCubit();
    cubit.selectedpack == false;
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: BlocConsumer<AddStickerToPackCubit, AddStickerToPackState>(listener: (context, state) {
          if (state is Readingdata) {
            listPack = state.list;
          }
        }, builder: (context, state) {
          return Column(
            children: [
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 26),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    GestureDetector(
                        onTap: () {
                          Navigator.pop(context);
                        },
                        child: SvgPicture.asset("assets/icons/ic_backBtn.svg")),
                    GestureDetector(
                        onTap: () {
                          AppNavigate.replacePage(context, const HomePage());
                        },
                        child: SvgPicture.asset("assets/icons/ic_home.svg"))
                  ],
                ),
              ),
              // Align(
              //   alignment: Alignment.centerRight,
              //   child: Container(
              //     margin: EdgeInsets.only(right: 16, bottom: 28),
              //     width: 90,
              //     height: 36,
              //     decoration:
              //         BoxDecoration(color: Color(0xFFFF8A65), borderRadius: BorderRadius.all(Radius.circular(10))),
              //     child: Row(
              //       mainAxisAlignment: MainAxisAlignment.spaceAround,
              //       children: [
              //         GestureDetector(
              //           onTap: () {},
              //           child: SvgPicture.asset("assets/icons/save_sticker.svg"),
              //         ),
              //         GestureDetector(
              //           onTap: () {},
              //           child: SvgPicture.asset("assets/icons/share_btn.svg"),
              //         ),
              //       ],
              //     ),
              //   ),
              // ),

              Expanded(
                  flex: 7,
                  child: Center(
                    child: AspectRatio(aspectRatio: 9 / 10, child: Image.memory(widget.imageFile!)),
                  )),
              Container(
                margin: EdgeInsets.only(bottom: 14, top: 34),
                padding: const EdgeInsets.only(left: 15),
                alignment: Alignment.topLeft,
                child: Text(
                  AppLocalizations.of(context)!.your_sticker_packs,
                  style: AppStyle.DEFAUlT_12_CR,
                ),
              ),
              Expanded(
                flex: 2,
                child: Row(
                  children: [
                    Container(
                      padding: const EdgeInsets.symmetric(horizontal: 15),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            AppLocalizations.of(context)!.create_pack,
                            style: AppStyle.DEFAUlT_CONTENT_TITLE_PACK_STICKER,
                          ),
                          SizedBox(height: 5),
                          GestureDetector(
                            onTap: () {
                              cubit.createPack();
                            },
                            child: SvgPicture.asset(
                              "assets/icons/create_pack.svg",
                              width: 65,
                              height: 65,
                            ),
                          ),
                        ],
                      ),
                    ),
                    Expanded(
                      child: ListView.builder(
                        physics: BouncingScrollPhysics(),
                        scrollDirection: Axis.horizontal,
                        shrinkWrap: true,
                        itemCount: listPack?.length,
                        itemBuilder: (context, index) => CustomChooseSticker(
                          linkSticker: listPack![index].urlImage ?? "",
                          titlePack: listPack![index].title ?? "",
                          status: listPack![index].status ?? false,
                          update: () {
                            listPack![index].status = listPack![index].status == false;
                            if (listPack![index].status == true) {
                              countSelectedPack++;
                            } else {
                              countSelectedPack--;
                            }
                            setState(() {});
                          },
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              BlocConsumer<AddStickerToPackCubit, AddStickerToPackState>(
                listener: (context, state) {
                  if (state is InsertData) {
                    stickerChild = state.listchild;
                  }
                },
                bloc: cubit,
                builder: (context, state) {
                  return GestureDetector(
                    onTap: () {
                      countSelectedPack > 0
                          ? AppNavigate.navigatePage(
                              context,
                              PackLibraryPage(
                                addPackCubit: cubit,
                              ))
                          : null;
                    },
                    child: Container(
                      margin: EdgeInsets.only(top: 25, bottom: 81),
                      width: 164,
                      padding: EdgeInsets.symmetric(horizontal: 25, vertical: 9),
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                            colors: countSelectedPack > 0
                                ? [Color(0xFFDE225B), Color(0xFFE46D39)]
                                : [Color(0xFFDE225B).withOpacity(0.3), Color(0xFFE46D39).withOpacity(0.3)]),
                        borderRadius: BorderRadius.all(Radius.circular(20)),
                      ),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceAround,
                        children: [
                          Text(AppLocalizations.of(context)!.add_to_pack, style: AppStyle.DEFAUlT_12),
                          SvgPicture.asset("assets/icons/ic_add.svg"),
                        ],
                      ),
                    ),
                  );
                },
              )
            ],
          );
        }),
      ),
    );
  }
}
